<?php 
$title = 'My projects';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p style="float:right;"><a class="btn btn-primary btn-lg active" href="<?php echo $this->url('project', array( 
        'action'=>'add'));?>">Add new project</a></p>

<table class="table table-bordered">
<tr>
    <th>Project name</th>
    <th>Description</th>
    <th>Action</th>
</tr>
<?php  foreach($projects as $project) : ?>
<tr>
    <td><?php echo $this->escapeHtml($project->title);?></td>
    <td><?php echo $this->escapeHtml($project->artist);?></td>
    <td style="width: 110px;">
        <a class="btn btn-default btn-lg active" href="<?php echo $this->url('project',
            array('action'=>'edit', 'id' => $project->id));?>">Edit</a>
        <a class="btn btn-default btn-lg active" href="<?php echo $this->url('project',
            array('action'=>'delete', 'id' => $project->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
